linters:
  disable-all: false
  enable:
    - gofmt
    - whitespace
    - dupl
    - gocognit
    - unparam
    - gocyclo
    - gocritic
    - nakedret
    - asciicheck
    - dogsled
    - misspell
    - nestif
    - nolintlint
    - stylecheck
    - errcheck
    - lll
    - govet
    - gosimple
    - staticcheck

run:
  timeout: 15m

linters-settings:
  lll:
    line-length: 240
  gci:
    sections:
      - standard
      - default
      - blank
    skip-generated: true
